/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    ERC20Mock: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
            {
              internalType: "string",
              name: "_symbol",
              type: "string",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "allowance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
          ],
          name: "ERC20InsufficientAllowance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
          ],
          name: "ERC20InsufficientBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "approver",
              type: "address",
            },
          ],
          name: "ERC20InvalidApprover",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
          ],
          name: "ERC20InvalidReceiver",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "ERC20InvalidSender",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "ERC20InvalidSpender",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "allowance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "transfer",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        allowance: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        approve: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        balanceOf: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        decimals: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        name: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        symbol: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        totalSupply: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        transfer: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        transferFrom: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
      },
    },
    StreamFactory: {
      address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      abi: [
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_streamCreationFee",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_streamCreationFeeToken",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_exitFeePercent",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_minWaitingDuration",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_minBootstrappingDuration",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_minStreamDuration",
              type: "uint256",
            },
            {
              internalType: "address[]",
              name: "_acceptedTokens",
              type: "address[]",
            },
            {
              internalType: "address",
              name: "_feeCollector",
              type: "address",
            },
            {
              internalType: "address",
              name: "_protocolAdmin",
              type: "address",
            },
            {
              internalType: "string",
              name: "_tosVersion",
              type: "string",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "subscriber",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "purchased",
              type: "uint256",
            },
          ],
          name: "Exited",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "newFeeCollector",
              type: "address",
            },
          ],
          name: "FeeCollectorUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "bool",
              name: "frozen",
              type: "bool",
            },
          ],
          name: "FrozenStateUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [],
          name: "ParamsUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "newProtocolAdmin",
              type: "address",
            },
          ],
          name: "ProtocolAdminUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "streamOutAmount",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "bootstrappingStartTime",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "streamStartTime",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "streamEndTime",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "streamAddress",
              type: "address",
            },
          ],
          name: "StreamCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "spentIn",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "outRemaining",
              type: "uint256",
            },
          ],
          name: "StreamFinalized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "enum IStreamTypes.Status",
              name: "mainStatus",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "enum IStreamTypes.FinalizedStatus",
              name: "finalized",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "lastUpdated",
              type: "uint256",
            },
          ],
          name: "StreamSynced",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "subscriber",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountIn",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newShares",
              type: "uint256",
            },
          ],
          name: "Subscribed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "subscriber",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountIn",
              type: "uint256",
            },
          ],
          name: "Withdrawn",
          type: "event",
        },
        {
          inputs: [],
          name: "NATIVE_TOKEN",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "acceptedTokens",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_streamOutAmount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_streamOutDenom",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_bootstrappingStartTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_streamStartTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_streamEndTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_threshold",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
            {
              internalType: "address",
              name: "_inDenom",
              type: "address",
            },
            {
              internalType: "string",
              name: "_tosVersion",
              type: "string",
            },
            {
              internalType: "bytes32",
              name: "_salt",
              type: "bytes32",
            },
          ],
          name: "createStream",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "frozen",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "isAcceptedToken",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "streamAddress",
              type: "address",
            },
          ],
          name: "isStream",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "params",
          outputs: [
            {
              internalType: "uint256",
              name: "streamCreationFee",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "streamCreationFeeToken",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "exitFeePercent",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minWaitingDuration",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minBootstrappingDuration",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minStreamDuration",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "feeCollector",
              type: "address",
            },
            {
              internalType: "address",
              name: "protocolAdmin",
              type: "address",
            },
            {
              internalType: "string",
              name: "tosVersion",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "_salt",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "bytecodeHash",
              type: "bytes32",
            },
          ],
          name: "predictAddress",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bool",
              name: "_frozen",
              type: "bool",
            },
          ],
          name: "setFrozen",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "streamId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "streams",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "tokens_to_add",
              type: "address[]",
            },
            {
              internalType: "address[]",
              name: "tokens_to_remove",
              type: "address[]",
            },
          ],
          name: "updateAcceptedTokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_feeCollector",
              type: "address",
            },
          ],
          name: "updateFeeCollector",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_streamCreationFee",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_exitFeePercent",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_minWaitingDuration",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_minBootstrappingDuration",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_minStreamDuration",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_tosVersion",
              type: "string",
            },
          ],
          name: "updateParams",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_protocolAdmin",
              type: "address",
            },
          ],
          name: "updateProtocolAdmin",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
